### ISSUE TITLE
Installer doesn't check result of ST2 install

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/bwc-installer#19]
This section is a problem - if the ST2 community install fails, the script doesn't check the exit code https://github.com/StackStorm/bwc-installer/blob/master/scripts/bwc-installer.sh#L182

If a user does not have SSHD running, then the ST2 verify step fails, and that script exits with return code 2. But we print a message "StackStorm Community version installed successfully", and carry on like nothing happened. We should detect that failure, and bail out at that point.

Otherwise the installer carries on, but then things break later because Mistral didn't get installed

Example installation output:
<snip>
```
.
id: 5840f86fef6a23430998b122
status: failed
parameters: 
  cmd: uname -a
  hosts: 127.0.0.1
result: 
  error: "Unable to connect to any one of the hosts: [u'127.0.0.1'].

 connect_errors={
  "127.0.0.1": {
    "failed": true, 
    "traceback": "Traceback (most recent call last):\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/ssh/parallel_ssh.py\", line 242, in _connect\n    client.connect()\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/ssh/paramiko_ssh.py\", line 144, in connect\n    self.client = self._connect(host=self.hostname, socket=self.bastion_socket)\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/ssh/paramiko_ssh.py\", line 584, in _connect\n    client.connect(**conninfo)\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/paramiko/client.py\", line 324, in connect\n    raise NoValidConnectionsError(errors)\nNoValidConnectionsError: [Errno None] Unable to connect to port 22 on 127.0.0.1\n", 
    "timeout": false, 
    "succeeded": false, 
    "stdout": "", 
    "stderr": "", 
    "error": "Failed connecting to host 127.0.0.1.: ", 
    "return_code": 255
  }
}"
  traceback: "  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/container/base.py", line 89, in _do_run
    runner.pre_run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/ssh/paramiko_ssh_runner.py", line 159, in pre_run
    self._parallel_ssh_client = ParallelSSHClient(**client_kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/ssh/parallel_ssh.py", line 60, in __init__
    connect_results = self.connect(raise_on_any_error=raise_on_any_error)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/ssh/parallel_ssh.py", line 90, in connect
    raise NoHostsConnectedToException(msg)
"
############### ERROR ###############
# Failed on step - Verify st2 #
#####################################
StackStorm Community version installed successfully.
Downloading deployment script from: https://raw.githubusercontent.com/StackStorm/bwc-installer/master/scripts/bwc-installer-deb.sh
Running deployment script for Brocade Workflow Composer ...
```

**Comment by LindsayHill** [comment]
Fixed by https://github.com/StackStorm/bwc-installer/pull/20
